<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WpfPrism_Demo</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="新文件夹\**" />
    <EmbeddedResource Remove="新文件夹\**" />
    <None Remove="新文件夹\**" />
    <Page Remove="新文件夹\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\Module.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModuleA.Plugin\ModuleA.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="app.storage.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
