<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>WpfPrism_Demo</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>..\Icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.Core" Version="8.1.97" />
		<PackageReference Include="Prism.DryIoc" Version="8.1.97" />
		<PackageReference Include="Prism.Wpf" Version="8.1.97" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ModuleA.Plugin\ModuleA.Plugin.csproj" />
		<!-- 把整个Modules目录全部作为内容，递归复制，Build、Publish都会输出 -->
	</ItemGroup>
	
	
	<ItemGroup>
		<!--匹配 Modules 文件夹下所有文件-->
		<Content Include="Modules\**\*">
			<!--编译时，有变动就复制到 bin 输出目录，保留原有目录结构；-->
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<!--publish 发布时同样复制这些文件-->
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<None Update="app.storage.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
